/*
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file was automatically generated by the code_generation module.
 * Any changes made to this file will be lost when regenerated.
 *
 * To modify this file, edit the corresponding template in:
 * code_generation/templates/functions/entry_points.mako
 */

<%namespace name="utils" file="utils.mako"/>

#include "transport_manager.h"
#include "xrtransport/transport/transport.h"
#include "xrtransport/serialization/serializer.h"
#include "xrtransport/serialization/deserializer.h"
#include "xrtransport/util.h"

#ifdef _MSC_VER
#define XRAPI_ATTR __declspec(dllexport)
#endif
#define XR_EXTENSION_PROTOTYPES
#include <openxr/openxr.h>

using namespace xrtransport;

extern "C" {

<%utils:for_grouped_functions args="function">
${function.declaration()} {
    auto& transport = get_transport();
    auto msg_out = transport.start_message(FUNCTION_CALL);
    uint32_t function_id = ${function.id};
    serialize(&function_id, msg_out.stream);
    % for param in function.params:
    ${utils.serialize_member(param, binding_prefix='', stream_var='msg_out.stream')}
    % endfor

    auto msg_in = transport.await_message(FUNCTION_RETURN);
    XrResult result;
    deserialize(&result, msg_in.stream);
    % for param in function.params:
    ${utils.deserialize_member(param, binding_prefix='', stream_var='msg_in.stream', in_place_var='true')}
    % endfor

    return result;
}
</%utils:for_grouped_functions>

} // extern "C"