/*
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file was automatically generated by the code_generation module.
 * Any changes made to this file will be lost when regenerated.
 *
 * To modify this file, edit the corresponding template in:
 * code_generation/templates/extensions/extension_functions.mako
 */
#ifndef XRTRANSPORT_EXTENSION_FUNCTIONS_H
#define XRTRANSPORT_EXTENSION_FUNCTIONS_H

#include <unordered_map>
#include <string>
#include <vector>

namespace xrtransport {

static const std::unordered_map<std::string, std::vector<std::string>> extension_functions = {
#ifdef XRTRANSPORT_EXT_XR_KHR_android_thread_settings
    {"XR_KHR_android_thread_settings", {
        "xrSetAndroidApplicationThreadKHR",
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_android_thread_settings
#ifdef XRTRANSPORT_EXT_XR_KHR_android_surface_swapchain
    {"XR_KHR_android_surface_swapchain", {
        "xrCreateSwapchainAndroidSurfaceKHR",
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_android_surface_swapchain
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_cube
    {"XR_KHR_composition_layer_cube", {
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_cube
#ifdef XRTRANSPORT_EXT_XR_KHR_android_create_instance
    {"XR_KHR_android_create_instance", {
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_android_create_instance
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_depth
    {"XR_KHR_composition_layer_depth", {
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_depth
#ifdef XRTRANSPORT_EXT_XR_KHR_vulkan_swapchain_format_list
    {"XR_KHR_vulkan_swapchain_format_list", {
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_vulkan_swapchain_format_list
#ifdef XRTRANSPORT_EXT_XR_EXT_performance_settings
    {"XR_EXT_performance_settings", {
        "xrPerfSettingsSetPerformanceLevelEXT",
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_performance_settings
#ifdef XRTRANSPORT_EXT_XR_EXT_thermal_query
    {"XR_EXT_thermal_query", {
        "xrThermalGetTemperatureTrendEXT",
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_thermal_query
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_cylinder
    {"XR_KHR_composition_layer_cylinder", {
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_cylinder
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_equirect
    {"XR_KHR_composition_layer_equirect", {
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_equirect
#ifdef XRTRANSPORT_EXT_XR_EXT_debug_utils
    {"XR_EXT_debug_utils", {
        "xrSetDebugUtilsObjectNameEXT",
        "xrCreateDebugUtilsMessengerEXT",
        "xrDestroyDebugUtilsMessengerEXT",
        "xrSubmitDebugUtilsMessageEXT",
        "xrSessionBeginDebugUtilsLabelRegionEXT",
        "xrSessionEndDebugUtilsLabelRegionEXT",
        "xrSessionInsertDebugUtilsLabelEXT",
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_debug_utils
#ifdef XRTRANSPORT_EXT_XR_KHR_opengl_enable
    {"XR_KHR_opengl_enable", {
        "xrGetOpenGLGraphicsRequirementsKHR",
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_opengl_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_opengl_es_enable
    {"XR_KHR_opengl_es_enable", {
        "xrGetOpenGLESGraphicsRequirementsKHR",
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_opengl_es_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_vulkan_enable
    {"XR_KHR_vulkan_enable", {
        "xrGetVulkanInstanceExtensionsKHR",
        "xrGetVulkanDeviceExtensionsKHR",
        "xrGetVulkanGraphicsDeviceKHR",
        "xrGetVulkanGraphicsRequirementsKHR",
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_vulkan_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_D3D11_enable
    {"XR_KHR_D3D11_enable", {
        "xrGetD3D11GraphicsRequirementsKHR",
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_D3D11_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_D3D12_enable
    {"XR_KHR_D3D12_enable", {
        "xrGetD3D12GraphicsRequirementsKHR",
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_D3D12_enable
#ifdef XRTRANSPORT_EXT_XR_KHR_metal_enable
    {"XR_KHR_metal_enable", {
        "xrGetMetalGraphicsRequirementsKHR",
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_metal_enable
#ifdef XRTRANSPORT_EXT_XR_EXT_eye_gaze_interaction
    {"XR_EXT_eye_gaze_interaction", {
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_eye_gaze_interaction
#ifdef XRTRANSPORT_EXT_XR_KHR_visibility_mask
    {"XR_KHR_visibility_mask", {
        "xrGetVisibilityMaskKHR",
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_visibility_mask
#ifdef XRTRANSPORT_EXT_XR_EXTX_overlay
    {"XR_EXTX_overlay", {
    }},
#endif // XRTRANSPORT_EXT_XR_EXTX_overlay
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_color_scale_bias
    {"XR_KHR_composition_layer_color_scale_bias", {
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_color_scale_bias
#ifdef XRTRANSPORT_EXT_XR_KHR_win32_convert_performance_counter_time
    {"XR_KHR_win32_convert_performance_counter_time", {
        "xrConvertWin32PerformanceCounterToTimeKHR",
        "xrConvertTimeToWin32PerformanceCounterKHR",
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_win32_convert_performance_counter_time
#ifdef XRTRANSPORT_EXT_XR_KHR_convert_timespec_time
    {"XR_KHR_convert_timespec_time", {
        "xrConvertTimespecTimeToTimeKHR",
        "xrConvertTimeToTimespecTimeKHR",
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_convert_timespec_time
#ifdef XRTRANSPORT_EXT_XR_MSFT_spatial_anchor
    {"XR_MSFT_spatial_anchor", {
        "xrCreateSpatialAnchorMSFT",
        "xrCreateSpatialAnchorSpaceMSFT",
        "xrDestroySpatialAnchorMSFT",
    }},
#endif // XRTRANSPORT_EXT_XR_MSFT_spatial_anchor
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_image_layout
    {"XR_FB_composition_layer_image_layout", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_image_layout
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_alpha_blend
    {"XR_FB_composition_layer_alpha_blend", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_alpha_blend
#ifdef XRTRANSPORT_EXT_XR_EXT_view_configuration_depth_range
    {"XR_EXT_view_configuration_depth_range", {
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_view_configuration_depth_range
#ifdef XRTRANSPORT_EXT_XR_EXT_conformance_automation
    {"XR_EXT_conformance_automation", {
        "xrSetInputDeviceActiveEXT",
        "xrSetInputDeviceStateBoolEXT",
        "xrSetInputDeviceStateFloatEXT",
        "xrSetInputDeviceStateVector2fEXT",
        "xrSetInputDeviceLocationEXT",
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_conformance_automation
#ifdef XRTRANSPORT_EXT_XR_MNDX_egl_enable
    {"XR_MNDX_egl_enable", {
    }},
#endif // XRTRANSPORT_EXT_XR_MNDX_egl_enable
#ifdef XRTRANSPORT_EXT_XR_MSFT_spatial_graph_bridge
    {"XR_MSFT_spatial_graph_bridge", {
        "xrCreateSpatialGraphNodeSpaceMSFT",
        "xrTryCreateSpatialGraphStaticNodeBindingMSFT",
        "xrDestroySpatialGraphNodeBindingMSFT",
        "xrGetSpatialGraphNodeBindingPropertiesMSFT",
    }},
#endif // XRTRANSPORT_EXT_XR_MSFT_spatial_graph_bridge
#ifdef XRTRANSPORT_EXT_XR_EXT_hand_tracking
    {"XR_EXT_hand_tracking", {
        "xrCreateHandTrackerEXT",
        "xrDestroyHandTrackerEXT",
        "xrLocateHandJointsEXT",
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_hand_tracking
#ifdef XRTRANSPORT_EXT_XR_MSFT_hand_tracking_mesh
    {"XR_MSFT_hand_tracking_mesh", {
        "xrCreateHandMeshSpaceMSFT",
        "xrUpdateHandMeshMSFT",
    }},
#endif // XRTRANSPORT_EXT_XR_MSFT_hand_tracking_mesh
#ifdef XRTRANSPORT_EXT_XR_MSFT_secondary_view_configuration
    {"XR_MSFT_secondary_view_configuration", {
    }},
#endif // XRTRANSPORT_EXT_XR_MSFT_secondary_view_configuration
#ifdef XRTRANSPORT_EXT_XR_MSFT_controller_model
    {"XR_MSFT_controller_model", {
        "xrGetControllerModelKeyMSFT",
        "xrLoadControllerModelMSFT",
        "xrGetControllerModelPropertiesMSFT",
        "xrGetControllerModelStateMSFT",
    }},
#endif // XRTRANSPORT_EXT_XR_MSFT_controller_model
#ifdef XRTRANSPORT_EXT_XR_MSFT_perception_anchor_interop
    {"XR_MSFT_perception_anchor_interop", {
        "xrCreateSpatialAnchorFromPerceptionAnchorMSFT",
        "xrTryGetPerceptionAnchorFromSpatialAnchorMSFT",
    }},
#endif // XRTRANSPORT_EXT_XR_MSFT_perception_anchor_interop
#ifdef XRTRANSPORT_EXT_XR_EPIC_view_configuration_fov
    {"XR_EPIC_view_configuration_fov", {
    }},
#endif // XRTRANSPORT_EXT_XR_EPIC_view_configuration_fov
#ifdef XRTRANSPORT_EXT_XR_MSFT_holographic_window_attachment
    {"XR_MSFT_holographic_window_attachment", {
    }},
#endif // XRTRANSPORT_EXT_XR_MSFT_holographic_window_attachment
#ifdef XRTRANSPORT_EXT_XR_MSFT_composition_layer_reprojection
    {"XR_MSFT_composition_layer_reprojection", {
        "xrEnumerateReprojectionModesMSFT",
    }},
#endif // XRTRANSPORT_EXT_XR_MSFT_composition_layer_reprojection
#ifdef XRTRANSPORT_EXT_XR_FB_android_surface_swapchain_create
    {"XR_FB_android_surface_swapchain_create", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_android_surface_swapchain_create
#ifdef XRTRANSPORT_EXT_XR_FB_swapchain_update_state
    {"XR_FB_swapchain_update_state", {
        "xrUpdateSwapchainFB",
        "xrGetSwapchainStateFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_swapchain_update_state
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_secure_content
    {"XR_FB_composition_layer_secure_content", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_secure_content
#ifdef XRTRANSPORT_EXT_XR_FB_body_tracking
    {"XR_FB_body_tracking", {
        "xrCreateBodyTrackerFB",
        "xrDestroyBodyTrackerFB",
        "xrLocateBodyJointsFB",
        "xrGetBodySkeletonFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_body_tracking
#ifdef XRTRANSPORT_EXT_XR_EXT_dpad_binding
    {"XR_EXT_dpad_binding", {
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_dpad_binding
#ifdef XRTRANSPORT_EXT_XR_VALVE_analog_threshold
    {"XR_VALVE_analog_threshold", {
    }},
#endif // XRTRANSPORT_EXT_XR_VALVE_analog_threshold
#ifdef XRTRANSPORT_EXT_XR_EXT_hand_joints_motion_range
    {"XR_EXT_hand_joints_motion_range", {
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_hand_joints_motion_range
#ifdef XRTRANSPORT_EXT_XR_KHR_loader_init
    {"XR_KHR_loader_init", {
        "xrInitializeLoaderKHR",
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_loader_init
#ifdef XRTRANSPORT_EXT_XR_KHR_loader_init_android
    {"XR_KHR_loader_init_android", {
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_loader_init_android
#ifdef XRTRANSPORT_EXT_XR_KHR_vulkan_enable2
    {"XR_KHR_vulkan_enable2", {
        "xrCreateVulkanInstanceKHR",
        "xrCreateVulkanDeviceKHR",
        "xrGetVulkanGraphicsDevice2KHR",
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_vulkan_enable2
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_equirect2
    {"XR_KHR_composition_layer_equirect2", {
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_equirect2
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_understanding
    {"XR_MSFT_scene_understanding", {
        "xrEnumerateSceneComputeFeaturesMSFT",
        "xrCreateSceneObserverMSFT",
        "xrDestroySceneObserverMSFT",
        "xrCreateSceneMSFT",
        "xrDestroySceneMSFT",
        "xrComputeNewSceneMSFT",
        "xrGetSceneComputeStateMSFT",
        "xrGetSceneComponentsMSFT",
        "xrLocateSceneComponentsMSFT",
        "xrGetSceneMeshBuffersMSFT",
    }},
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_understanding
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_understanding_serialization
    {"XR_MSFT_scene_understanding_serialization", {
        "xrDeserializeSceneMSFT",
        "xrGetSerializedSceneFragmentDataMSFT",
    }},
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_understanding_serialization
#ifdef XRTRANSPORT_EXT_XR_FB_display_refresh_rate
    {"XR_FB_display_refresh_rate", {
        "xrEnumerateDisplayRefreshRatesFB",
        "xrGetDisplayRefreshRateFB",
        "xrRequestDisplayRefreshRateFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_display_refresh_rate
#ifdef XRTRANSPORT_EXT_XR_HTCX_vive_tracker_interaction
    {"XR_HTCX_vive_tracker_interaction", {
        "xrEnumerateViveTrackerPathsHTCX",
    }},
#endif // XRTRANSPORT_EXT_XR_HTCX_vive_tracker_interaction
#ifdef XRTRANSPORT_EXT_XR_HTC_facial_tracking
    {"XR_HTC_facial_tracking", {
        "xrCreateFacialTrackerHTC",
        "xrDestroyFacialTrackerHTC",
        "xrGetFacialExpressionsHTC",
    }},
#endif // XRTRANSPORT_EXT_XR_HTC_facial_tracking
#ifdef XRTRANSPORT_EXT_XR_FB_color_space
    {"XR_FB_color_space", {
        "xrEnumerateColorSpacesFB",
        "xrSetColorSpaceFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_color_space
#ifdef XRTRANSPORT_EXT_XR_FB_hand_tracking_mesh
    {"XR_FB_hand_tracking_mesh", {
        "xrGetHandMeshFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_hand_tracking_mesh
#ifdef XRTRANSPORT_EXT_XR_FB_hand_tracking_aim
    {"XR_FB_hand_tracking_aim", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_hand_tracking_aim
#ifdef XRTRANSPORT_EXT_XR_FB_hand_tracking_capsules
    {"XR_FB_hand_tracking_capsules", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_hand_tracking_capsules
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity
    {"XR_FB_spatial_entity", {
        "xrCreateSpatialAnchorFB",
        "xrGetSpaceUuidFB",
        "xrEnumerateSpaceSupportedComponentsFB",
        "xrSetSpaceComponentStatusFB",
        "xrGetSpaceComponentStatusFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity
#ifdef XRTRANSPORT_EXT_XR_FB_foveation
    {"XR_FB_foveation", {
        "xrCreateFoveationProfileFB",
        "xrDestroyFoveationProfileFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_foveation
#ifdef XRTRANSPORT_EXT_XR_FB_foveation_configuration
    {"XR_FB_foveation_configuration", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_foveation_configuration
#ifdef XRTRANSPORT_EXT_XR_FB_keyboard_tracking
    {"XR_FB_keyboard_tracking", {
        "xrQuerySystemTrackedKeyboardFB",
        "xrCreateKeyboardSpaceFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_keyboard_tracking
#ifdef XRTRANSPORT_EXT_XR_FB_triangle_mesh
    {"XR_FB_triangle_mesh", {
        "xrCreateTriangleMeshFB",
        "xrDestroyTriangleMeshFB",
        "xrTriangleMeshGetVertexBufferFB",
        "xrTriangleMeshGetIndexBufferFB",
        "xrTriangleMeshBeginUpdateFB",
        "xrTriangleMeshEndUpdateFB",
        "xrTriangleMeshBeginVertexBufferUpdateFB",
        "xrTriangleMeshEndVertexBufferUpdateFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_triangle_mesh
#ifdef XRTRANSPORT_EXT_XR_FB_passthrough
    {"XR_FB_passthrough", {
        "xrCreatePassthroughFB",
        "xrDestroyPassthroughFB",
        "xrPassthroughStartFB",
        "xrPassthroughPauseFB",
        "xrCreatePassthroughLayerFB",
        "xrDestroyPassthroughLayerFB",
        "xrPassthroughLayerPauseFB",
        "xrPassthroughLayerResumeFB",
        "xrPassthroughLayerSetStyleFB",
        "xrCreateGeometryInstanceFB",
        "xrDestroyGeometryInstanceFB",
        "xrGeometryInstanceSetTransformFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_passthrough
#ifdef XRTRANSPORT_EXT_XR_FB_render_model
    {"XR_FB_render_model", {
        "xrEnumerateRenderModelPathsFB",
        "xrGetRenderModelPropertiesFB",
        "xrLoadRenderModelFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_render_model
#ifdef XRTRANSPORT_EXT_XR_KHR_binding_modification
    {"XR_KHR_binding_modification", {
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_binding_modification
#ifdef XRTRANSPORT_EXT_XR_VARJO_foveated_rendering
    {"XR_VARJO_foveated_rendering", {
    }},
#endif // XRTRANSPORT_EXT_XR_VARJO_foveated_rendering
#ifdef XRTRANSPORT_EXT_XR_VARJO_composition_layer_depth_test
    {"XR_VARJO_composition_layer_depth_test", {
    }},
#endif // XRTRANSPORT_EXT_XR_VARJO_composition_layer_depth_test
#ifdef XRTRANSPORT_EXT_XR_VARJO_environment_depth_estimation
    {"XR_VARJO_environment_depth_estimation", {
        "xrSetEnvironmentDepthEstimationVARJO",
    }},
#endif // XRTRANSPORT_EXT_XR_VARJO_environment_depth_estimation
#ifdef XRTRANSPORT_EXT_XR_VARJO_marker_tracking
    {"XR_VARJO_marker_tracking", {
        "xrSetMarkerTrackingVARJO",
        "xrSetMarkerTrackingTimeoutVARJO",
        "xrSetMarkerTrackingPredictionVARJO",
        "xrGetMarkerSizeVARJO",
        "xrCreateMarkerSpaceVARJO",
    }},
#endif // XRTRANSPORT_EXT_XR_VARJO_marker_tracking
#ifdef XRTRANSPORT_EXT_XR_VARJO_view_offset
    {"XR_VARJO_view_offset", {
        "xrSetViewOffsetVARJO",
    }},
#endif // XRTRANSPORT_EXT_XR_VARJO_view_offset
#ifdef XRTRANSPORT_EXT_XR_ML_frame_end_info
    {"XR_ML_frame_end_info", {
    }},
#endif // XRTRANSPORT_EXT_XR_ML_frame_end_info
#ifdef XRTRANSPORT_EXT_XR_ML_global_dimmer
    {"XR_ML_global_dimmer", {
    }},
#endif // XRTRANSPORT_EXT_XR_ML_global_dimmer
#ifdef XRTRANSPORT_EXT_XR_ML_compat
    {"XR_ML_compat", {
        "xrCreateSpaceFromCoordinateFrameUIDML",
    }},
#endif // XRTRANSPORT_EXT_XR_ML_compat
#ifdef XRTRANSPORT_EXT_XR_ML_marker_understanding
    {"XR_ML_marker_understanding", {
        "xrCreateMarkerDetectorML",
        "xrDestroyMarkerDetectorML",
        "xrSnapshotMarkerDetectorML",
        "xrGetMarkerDetectorStateML",
        "xrGetMarkersML",
        "xrGetMarkerReprojectionErrorML",
        "xrGetMarkerLengthML",
        "xrGetMarkerNumberML",
        "xrGetMarkerStringML",
        "xrCreateMarkerSpaceML",
    }},
#endif // XRTRANSPORT_EXT_XR_ML_marker_understanding
#ifdef XRTRANSPORT_EXT_XR_ML_localization_map
    {"XR_ML_localization_map", {
        "xrEnableLocalizationEventsML",
        "xrQueryLocalizationMapsML",
        "xrRequestMapLocalizationML",
        "xrImportLocalizationMapML",
        "xrCreateExportedLocalizationMapML",
        "xrDestroyExportedLocalizationMapML",
        "xrGetExportedLocalizationMapDataML",
    }},
#endif // XRTRANSPORT_EXT_XR_ML_localization_map
#ifdef XRTRANSPORT_EXT_XR_ML_spatial_anchors
    {"XR_ML_spatial_anchors", {
        "xrCreateSpatialAnchorsAsyncML",
        "xrCreateSpatialAnchorsCompleteML",
        "xrGetSpatialAnchorStateML",
    }},
#endif // XRTRANSPORT_EXT_XR_ML_spatial_anchors
#ifdef XRTRANSPORT_EXT_XR_ML_spatial_anchors_storage
    {"XR_ML_spatial_anchors_storage", {
        "xrCreateSpatialAnchorsStorageML",
        "xrDestroySpatialAnchorsStorageML",
        "xrQuerySpatialAnchorsAsyncML",
        "xrQuerySpatialAnchorsCompleteML",
        "xrPublishSpatialAnchorsAsyncML",
        "xrPublishSpatialAnchorsCompleteML",
        "xrDeleteSpatialAnchorsAsyncML",
        "xrDeleteSpatialAnchorsCompleteML",
        "xrUpdateSpatialAnchorsExpirationAsyncML",
        "xrUpdateSpatialAnchorsExpirationCompleteML",
    }},
#endif // XRTRANSPORT_EXT_XR_ML_spatial_anchors_storage
#ifdef XRTRANSPORT_EXT_XR_ML_user_calibration
    {"XR_ML_user_calibration", {
        "xrEnableUserCalibrationEventsML",
    }},
#endif // XRTRANSPORT_EXT_XR_ML_user_calibration
#ifdef XRTRANSPORT_EXT_XR_MSFT_spatial_anchor_persistence
    {"XR_MSFT_spatial_anchor_persistence", {
        "xrCreateSpatialAnchorStoreConnectionMSFT",
        "xrDestroySpatialAnchorStoreConnectionMSFT",
        "xrPersistSpatialAnchorMSFT",
        "xrEnumeratePersistedSpatialAnchorNamesMSFT",
        "xrCreateSpatialAnchorFromPersistedNameMSFT",
        "xrUnpersistSpatialAnchorMSFT",
        "xrClearSpatialAnchorStoreMSFT",
    }},
#endif // XRTRANSPORT_EXT_XR_MSFT_spatial_anchor_persistence
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_marker
    {"XR_MSFT_scene_marker", {
        "xrGetSceneMarkerRawDataMSFT",
        "xrGetSceneMarkerDecodedStringMSFT",
    }},
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_marker
#ifdef XRTRANSPORT_EXT_XR_KHR_extended_struct_name_lengths
    {"XR_KHR_extended_struct_name_lengths", {
        "xrStructureTypeToString2KHR",
    }},
#endif // XRTRANSPORT_EXT_XR_KHR_extended_struct_name_lengths
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_query
    {"XR_FB_spatial_entity_query", {
        "xrQuerySpacesFB",
        "xrRetrieveSpaceQueryResultsFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_query
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_storage
    {"XR_FB_spatial_entity_storage", {
        "xrSaveSpaceFB",
        "xrEraseSpaceFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_storage
#ifdef XRTRANSPORT_EXT_XR_OCULUS_audio_device_guid
    {"XR_OCULUS_audio_device_guid", {
        "xrGetAudioOutputDeviceGuidOculus",
        "xrGetAudioInputDeviceGuidOculus",
    }},
#endif // XRTRANSPORT_EXT_XR_OCULUS_audio_device_guid
#ifdef XRTRANSPORT_EXT_XR_FB_foveation_vulkan
    {"XR_FB_foveation_vulkan", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_foveation_vulkan
#ifdef XRTRANSPORT_EXT_XR_FB_swapchain_update_state_android_surface
    {"XR_FB_swapchain_update_state_android_surface", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_swapchain_update_state_android_surface
#ifdef XRTRANSPORT_EXT_XR_FB_swapchain_update_state_opengl_es
    {"XR_FB_swapchain_update_state_opengl_es", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_swapchain_update_state_opengl_es
#ifdef XRTRANSPORT_EXT_XR_FB_swapchain_update_state_vulkan
    {"XR_FB_swapchain_update_state_vulkan", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_swapchain_update_state_vulkan
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_sharing
    {"XR_FB_spatial_entity_sharing", {
        "xrShareSpacesFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_sharing
#ifdef XRTRANSPORT_EXT_XR_FB_space_warp
    {"XR_FB_space_warp", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_space_warp
#ifdef XRTRANSPORT_EXT_XR_FB_haptic_amplitude_envelope
    {"XR_FB_haptic_amplitude_envelope", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_haptic_amplitude_envelope
#ifdef XRTRANSPORT_EXT_XR_FB_scene
    {"XR_FB_scene", {
        "xrGetSpaceBoundingBox2DFB",
        "xrGetSpaceBoundingBox3DFB",
        "xrGetSpaceSemanticLabelsFB",
        "xrGetSpaceBoundary2DFB",
        "xrGetSpaceRoomLayoutFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_scene
#ifdef XRTRANSPORT_EXT_XR_ALMALENCE_digital_lens_control
    {"XR_ALMALENCE_digital_lens_control", {
        "xrSetDigitalLensControlALMALENCE",
    }},
#endif // XRTRANSPORT_EXT_XR_ALMALENCE_digital_lens_control
#ifdef XRTRANSPORT_EXT_XR_FB_scene_capture
    {"XR_FB_scene_capture", {
        "xrRequestSceneCaptureFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_scene_capture
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_container
    {"XR_FB_spatial_entity_container", {
        "xrGetSpaceContainerFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_container
#ifdef XRTRANSPORT_EXT_XR_META_foveation_eye_tracked
    {"XR_META_foveation_eye_tracked", {
        "xrGetFoveationEyeTrackedStateMETA",
    }},
#endif // XRTRANSPORT_EXT_XR_META_foveation_eye_tracked
#ifdef XRTRANSPORT_EXT_XR_FB_face_tracking
    {"XR_FB_face_tracking", {
        "xrCreateFaceTrackerFB",
        "xrDestroyFaceTrackerFB",
        "xrGetFaceExpressionWeightsFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_face_tracking
#ifdef XRTRANSPORT_EXT_XR_FB_eye_tracking_social
    {"XR_FB_eye_tracking_social", {
        "xrCreateEyeTrackerFB",
        "xrDestroyEyeTrackerFB",
        "xrGetEyeGazesFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_eye_tracking_social
#ifdef XRTRANSPORT_EXT_XR_FB_passthrough_keyboard_hands
    {"XR_FB_passthrough_keyboard_hands", {
        "xrPassthroughLayerSetKeyboardHandsIntensityFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_passthrough_keyboard_hands
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_settings
    {"XR_FB_composition_layer_settings", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_settings
#ifdef XRTRANSPORT_EXT_XR_FB_haptic_pcm
    {"XR_FB_haptic_pcm", {
        "xrGetDeviceSampleRateFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_haptic_pcm
#ifdef XRTRANSPORT_EXT_XR_EXT_frame_synthesis
    {"XR_EXT_frame_synthesis", {
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_frame_synthesis
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_depth_test
    {"XR_FB_composition_layer_depth_test", {
    }},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_depth_test
#ifdef XRTRANSPORT_EXT_XR_META_local_dimming
    {"XR_META_local_dimming", {
    }},
#endif // XRTRANSPORT_EXT_XR_META_local_dimming
#ifdef XRTRANSPORT_EXT_XR_META_passthrough_preferences
    {"XR_META_passthrough_preferences", {
        "xrGetPassthroughPreferencesMETA",
    }},
#endif // XRTRANSPORT_EXT_XR_META_passthrough_preferences
#ifdef XRTRANSPORT_EXT_XR_META_virtual_keyboard
    {"XR_META_virtual_keyboard", {
        "xrCreateVirtualKeyboardMETA",
        "xrDestroyVirtualKeyboardMETA",
        "xrCreateVirtualKeyboardSpaceMETA",
        "xrSuggestVirtualKeyboardLocationMETA",
        "xrGetVirtualKeyboardScaleMETA",
        "xrSetVirtualKeyboardModelVisibilityMETA",
        "xrGetVirtualKeyboardModelAnimationStatesMETA",
        "xrGetVirtualKeyboardDirtyTexturesMETA",
        "xrGetVirtualKeyboardTextureDataMETA",
        "xrSendVirtualKeyboardInputMETA",
        "xrChangeVirtualKeyboardTextContextMETA",
    }},
#endif // XRTRANSPORT_EXT_XR_META_virtual_keyboard
#ifdef XRTRANSPORT_EXT_XR_OCULUS_external_camera
    {"XR_OCULUS_external_camera", {
        "xrEnumerateExternalCamerasOCULUS",
    }},
#endif // XRTRANSPORT_EXT_XR_OCULUS_external_camera
#ifdef XRTRANSPORT_EXT_XR_META_vulkan_swapchain_create_info
    {"XR_META_vulkan_swapchain_create_info", {
    }},
#endif // XRTRANSPORT_EXT_XR_META_vulkan_swapchain_create_info
#ifdef XRTRANSPORT_EXT_XR_META_performance_metrics
    {"XR_META_performance_metrics", {
        "xrEnumeratePerformanceMetricsCounterPathsMETA",
        "xrSetPerformanceMetricsStateMETA",
        "xrGetPerformanceMetricsStateMETA",
        "xrQueryPerformanceMetricsCounterMETA",
    }},
#endif // XRTRANSPORT_EXT_XR_META_performance_metrics
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_storage_batch
    {"XR_FB_spatial_entity_storage_batch", {
        "xrSaveSpaceListFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_storage_batch
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_user
    {"XR_FB_spatial_entity_user", {
        "xrCreateSpaceUserFB",
        "xrGetSpaceUserIdFB",
        "xrDestroySpaceUserFB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_user
#ifdef XRTRANSPORT_EXT_XR_META_headset_id
    {"XR_META_headset_id", {
    }},
#endif // XRTRANSPORT_EXT_XR_META_headset_id
#ifdef XRTRANSPORT_EXT_XR_META_recommended_layer_resolution
    {"XR_META_recommended_layer_resolution", {
        "xrGetRecommendedLayerResolutionMETA",
    }},
#endif // XRTRANSPORT_EXT_XR_META_recommended_layer_resolution
#ifdef XRTRANSPORT_EXT_XR_META_passthrough_color_lut
    {"XR_META_passthrough_color_lut", {
        "xrCreatePassthroughColorLutMETA",
        "xrDestroyPassthroughColorLutMETA",
        "xrUpdatePassthroughColorLutMETA",
    }},
#endif // XRTRANSPORT_EXT_XR_META_passthrough_color_lut
#ifdef XRTRANSPORT_EXT_XR_META_spatial_entity_mesh
    {"XR_META_spatial_entity_mesh", {
        "xrGetSpaceTriangleMeshMETA",
    }},
#endif // XRTRANSPORT_EXT_XR_META_spatial_entity_mesh
#ifdef XRTRANSPORT_EXT_XR_META_body_tracking_full_body
    {"XR_META_body_tracking_full_body", {
    }},
#endif // XRTRANSPORT_EXT_XR_META_body_tracking_full_body
#ifdef XRTRANSPORT_EXT_XR_META_passthrough_layer_resumed_event
    {"XR_META_passthrough_layer_resumed_event", {
    }},
#endif // XRTRANSPORT_EXT_XR_META_passthrough_layer_resumed_event
#ifdef XRTRANSPORT_EXT_XR_FB_face_tracking2
    {"XR_FB_face_tracking2", {
        "xrCreateFaceTracker2FB",
        "xrDestroyFaceTracker2FB",
        "xrGetFaceExpressionWeights2FB",
    }},
#endif // XRTRANSPORT_EXT_XR_FB_face_tracking2
#ifdef XRTRANSPORT_EXT_XR_META_spatial_entity_sharing
    {"XR_META_spatial_entity_sharing", {
        "xrShareSpacesMETA",
    }},
#endif // XRTRANSPORT_EXT_XR_META_spatial_entity_sharing
#ifdef XRTRANSPORT_EXT_XR_META_environment_depth
    {"XR_META_environment_depth", {
        "xrCreateEnvironmentDepthProviderMETA",
        "xrDestroyEnvironmentDepthProviderMETA",
        "xrStartEnvironmentDepthProviderMETA",
        "xrStopEnvironmentDepthProviderMETA",
        "xrCreateEnvironmentDepthSwapchainMETA",
        "xrDestroyEnvironmentDepthSwapchainMETA",
        "xrEnumerateEnvironmentDepthSwapchainImagesMETA",
        "xrGetEnvironmentDepthSwapchainStateMETA",
        "xrAcquireEnvironmentDepthImageMETA",
        "xrSetEnvironmentDepthHandRemovalMETA",
    }},
#endif // XRTRANSPORT_EXT_XR_META_environment_depth
#ifdef XRTRANSPORT_EXT_XR_QCOM_tracking_optimization_settings
    {"XR_QCOM_tracking_optimization_settings", {
        "xrSetTrackingOptimizationSettingsHintQCOM",
    }},
#endif // XRTRANSPORT_EXT_XR_QCOM_tracking_optimization_settings
#ifdef XRTRANSPORT_EXT_XR_HTC_passthrough
    {"XR_HTC_passthrough", {
        "xrCreatePassthroughHTC",
        "xrDestroyPassthroughHTC",
    }},
#endif // XRTRANSPORT_EXT_XR_HTC_passthrough
#ifdef XRTRANSPORT_EXT_XR_HTC_foveation
    {"XR_HTC_foveation", {
        "xrApplyFoveationHTC",
    }},
#endif // XRTRANSPORT_EXT_XR_HTC_foveation
#ifdef XRTRANSPORT_EXT_XR_HTC_anchor
    {"XR_HTC_anchor", {
        "xrCreateSpatialAnchorHTC",
        "xrGetSpatialAnchorNameHTC",
    }},
#endif // XRTRANSPORT_EXT_XR_HTC_anchor
#ifdef XRTRANSPORT_EXT_XR_HTC_body_tracking
    {"XR_HTC_body_tracking", {
        "xrCreateBodyTrackerHTC",
        "xrDestroyBodyTrackerHTC",
        "xrLocateBodyJointsHTC",
        "xrGetBodySkeletonHTC",
    }},
#endif // XRTRANSPORT_EXT_XR_HTC_body_tracking
#ifdef XRTRANSPORT_EXT_XR_EXT_active_action_set_priority
    {"XR_EXT_active_action_set_priority", {
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_active_action_set_priority
#ifdef XRTRANSPORT_EXT_XR_MNDX_force_feedback_curl
    {"XR_MNDX_force_feedback_curl", {
        "xrApplyForceFeedbackCurlMNDX",
    }},
#endif // XRTRANSPORT_EXT_XR_MNDX_force_feedback_curl
#ifdef XRTRANSPORT_EXT_XR_BD_body_tracking
    {"XR_BD_body_tracking", {
        "xrCreateBodyTrackerBD",
        "xrDestroyBodyTrackerBD",
        "xrLocateBodyJointsBD",
    }},
#endif // XRTRANSPORT_EXT_XR_BD_body_tracking
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_sensing
    {"XR_BD_spatial_sensing", {
        "xrEnumerateSpatialEntityComponentTypesBD",
        "xrGetSpatialEntityUuidBD",
        "xrGetSpatialEntityComponentDataBD",
        "xrCreateSenseDataProviderBD",
        "xrStartSenseDataProviderAsyncBD",
        "xrStartSenseDataProviderCompleteBD",
        "xrGetSenseDataProviderStateBD",
        "xrQuerySenseDataAsyncBD",
        "xrQuerySenseDataCompleteBD",
        "xrDestroySenseDataSnapshotBD",
        "xrGetQueriedSenseDataBD",
        "xrStopSenseDataProviderBD",
        "xrDestroySenseDataProviderBD",
        "xrCreateSpatialEntityAnchorBD",
        "xrDestroyAnchorBD",
        "xrGetAnchorUuidBD",
        "xrCreateAnchorSpaceBD",
    }},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_sensing
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_anchor
    {"XR_BD_spatial_anchor", {
        "xrCreateSpatialAnchorAsyncBD",
        "xrCreateSpatialAnchorCompleteBD",
        "xrPersistSpatialAnchorAsyncBD",
        "xrPersistSpatialAnchorCompleteBD",
        "xrUnpersistSpatialAnchorAsyncBD",
        "xrUnpersistSpatialAnchorCompleteBD",
    }},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_anchor
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_anchor_sharing
    {"XR_BD_spatial_anchor_sharing", {
        "xrShareSpatialAnchorAsyncBD",
        "xrShareSpatialAnchorCompleteBD",
        "xrDownloadSharedSpatialAnchorAsyncBD",
        "xrDownloadSharedSpatialAnchorCompleteBD",
    }},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_anchor_sharing
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_scene
    {"XR_BD_spatial_scene", {
        "xrCaptureSceneAsyncBD",
        "xrCaptureSceneCompleteBD",
    }},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_scene
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_mesh
    {"XR_BD_spatial_mesh", {
    }},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_mesh
#ifdef XRTRANSPORT_EXT_XR_BD_future_progress
    {"XR_BD_future_progress", {
    }},
#endif // XRTRANSPORT_EXT_XR_BD_future_progress
#ifdef XRTRANSPORT_EXT_XR_EXT_hand_tracking_data_source
    {"XR_EXT_hand_tracking_data_source", {
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_hand_tracking_data_source
#ifdef XRTRANSPORT_EXT_XR_EXT_plane_detection
    {"XR_EXT_plane_detection", {
        "xrCreatePlaneDetectorEXT",
        "xrDestroyPlaneDetectorEXT",
        "xrBeginPlaneDetectionEXT",
        "xrGetPlaneDetectionStateEXT",
        "xrGetPlaneDetectionsEXT",
        "xrGetPlanePolygonBufferEXT",
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_plane_detection
#ifdef XRTRANSPORT_EXT_XR_EXT_future
    {"XR_EXT_future", {
        "xrPollFutureEXT",
        "xrCancelFutureEXT",
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_future
#ifdef XRTRANSPORT_EXT_XR_EXT_user_presence
    {"XR_EXT_user_presence", {
    }},
#endif // XRTRANSPORT_EXT_XR_EXT_user_presence
#ifdef XRTRANSPORT_EXT_XR_ML_system_notifications
    {"XR_ML_system_notifications", {
        "xrSetSystemNotificationsML",
    }},
#endif // XRTRANSPORT_EXT_XR_ML_system_notifications
#ifdef XRTRANSPORT_EXT_XR_ML_world_mesh_detection
    {"XR_ML_world_mesh_detection", {
        "xrCreateWorldMeshDetectorML",
        "xrDestroyWorldMeshDetectorML",
        "xrRequestWorldMeshStateAsyncML",
        "xrRequestWorldMeshStateCompleteML",
        "xrGetWorldMeshBufferRecommendSizeML",
        "xrAllocateWorldMeshBufferML",
        "xrFreeWorldMeshBufferML",
        "xrRequestWorldMeshAsyncML",
        "xrRequestWorldMeshCompleteML",
    }},
#endif // XRTRANSPORT_EXT_XR_ML_world_mesh_detection
#ifdef XRTRANSPORT_EXT_XR_ML_facial_expression
    {"XR_ML_facial_expression", {
        "xrCreateFacialExpressionClientML",
        "xrDestroyFacialExpressionClientML",
        "xrGetFacialExpressionBlendShapePropertiesML",
    }},
#endif // XRTRANSPORT_EXT_XR_ML_facial_expression
#ifdef XRTRANSPORT_EXT_XR_META_simultaneous_hands_and_controllers
    {"XR_META_simultaneous_hands_and_controllers", {
        "xrResumeSimultaneousHandsAndControllersTrackingMETA",
        "xrPauseSimultaneousHandsAndControllersTrackingMETA",
    }},
#endif // XRTRANSPORT_EXT_XR_META_simultaneous_hands_and_controllers
#ifdef XRTRANSPORT_EXT_XR_META_colocation_discovery
    {"XR_META_colocation_discovery", {
        "xrStartColocationDiscoveryMETA",
        "xrStopColocationDiscoveryMETA",
        "xrStartColocationAdvertisementMETA",
        "xrStopColocationAdvertisementMETA",
    }},
#endif // XRTRANSPORT_EXT_XR_META_colocation_discovery
#ifdef XRTRANSPORT_EXT_XR_META_spatial_entity_group_sharing
    {"XR_META_spatial_entity_group_sharing", {
    }},
#endif // XRTRANSPORT_EXT_XR_META_spatial_entity_group_sharing
};

static const std::vector<std::string> core_functions = {
    "xrAcquireSwapchainImage",
    "xrApplyHapticFeedback",
    "xrAttachSessionActionSets",
    "xrBeginFrame",
    "xrBeginSession",
    "xrCreateAction",
    "xrCreateActionSet",
    "xrCreateActionSpace",
    "xrCreateInstance",
    "xrCreateReferenceSpace",
    "xrCreateSession",
    "xrCreateSwapchain",
    "xrDestroyAction",
    "xrDestroyActionSet",
    "xrDestroyInstance",
    "xrDestroySession",
    "xrDestroySpace",
    "xrDestroySwapchain",
    "xrEndFrame",
    "xrEndSession",
    "xrEnumerateApiLayerProperties",
    "xrEnumerateBoundSourcesForAction",
    "xrEnumerateEnvironmentBlendModes",
    "xrEnumerateInstanceExtensionProperties",
    "xrEnumerateReferenceSpaces",
    "xrEnumerateSwapchainFormats",
    "xrEnumerateSwapchainImages",
    "xrEnumerateViewConfigurationViews",
    "xrEnumerateViewConfigurations",
    "xrGetActionStateBoolean",
    "xrGetActionStateFloat",
    "xrGetActionStatePose",
    "xrGetActionStateVector2f",
    "xrGetCurrentInteractionProfile",
    "xrGetInputSourceLocalizedName",
    "xrGetInstanceProperties",
    "xrGetReferenceSpaceBoundsRect",
    "xrGetSystem",
    "xrGetSystemProperties",
    "xrGetViewConfigurationProperties",
    "xrLocateSpace",
    "xrLocateSpaces",
    "xrLocateViews",
    "xrPathToString",
    "xrPollEvent",
    "xrReleaseSwapchainImage",
    "xrRequestExitSession",
    "xrResultToString",
    "xrStopHapticFeedback",
    "xrStringToPath",
    "xrStructureTypeToString",
    "xrSuggestInteractionProfileBindings",
    "xrSyncActions",
    "xrWaitFrame",
    "xrWaitSwapchainImage",
};

} // namespace xrtransport

#endif // XRTRANSPORT_EXTENSION_FUNCTIONS_H